<?php $this->layout('layouts/app') ?>

<?php $this->start('main') ?>
<section id="contact" class="contact-section">
    <div class="contact-wrapper">
        <div class="contact-header">
            <h2 class="contact-heading">
                Contact Us
            </h2>
            <p class="contact-subheading">
                Have questions? Send us a message and we'll get back to you as soon as possible.
            </p>
        </div>

        <div class="contact-form-wrapper">
            <form id="contact-form" method="POST" action="/contact" class="contact-form">
                <?php // CSRF tokens (generated by Slim\Csrf\Guard) ?>
                <input type="hidden" name="<?= htmlspecialchars($csrf_name_key ?? '') ?>" value="<?= htmlspecialchars($csrf_name ?? '') ?>">
                <input type="hidden" name="<?= htmlspecialchars($csrf_value_key ?? '') ?>" value="<?= htmlspecialchars($csrf_value ?? '') ?>">
                <div class="contact-fields">
                    <!-- Left Column -->
                    <div class="contact-column">
                        <!-- Full Name -->
                        <div>
                            <label for="name" class="form-label">Full Name <span class="text-red-500">*</span></label>
                            <input type="text" name="name" id="name" required minlength="2" maxlength="100"
                                class="form-input">
                        </div>

                        <!-- Email -->
                        <div>
                            <label for="email" class="form-label">Email <span class="text-red-500">*</span></label>
                            <input type="email" name="email" id="email" required
                                class="form-input">
                        </div>

                        <!-- Phone Number -->
                        <div>
                            <label for="phone" class="form-label">Phone Number</label>
                            <input type="tel" name="phone" id="phone"
                                class="form-input"
                                placeholder="+1 (555) 123-4567">
                        </div>

                        <!-- Company Name -->
                        <div>
                            <label for="company" class="form-label">Company Name</label>
                            <input type="text" name="company" id="company" maxlength="100"
                                class="form-input">
                        </div>

                        <!-- Project Type -->
                        <div>
                            <label for="project_type" class="form-label">Project Type <span class="text-red-500">*</span></label>
                            <select name="project_type" id="project_type" required
                                class="form-input">
                                <option value="" disabled selected>Select project type</option>
                                <option value="web">Web Development</option>
                                <option value="software">Software Development</option>
                                <option value="consulting">Consulting</option>
                                <option value="other">Other</option>
                            </select>
                        </div>
                    </div>

                    <!-- Right Column -->
                    <div class="contact-column contact-column--right">
                        <!-- Project Description -->
                        <div class="flex flex-col">
                            <label for="message" class="form-label">Project Description <span class="text-red-500">*</span></label>
                            <div class="flex-1">
                                <textarea id="message" name="message" rows="8" required minlength="10" maxlength="2000"
                                     class="form-input"
                                    placeholder="Tell us about your project..."></textarea>
                            </div>
                            <div class="text-right text-xs text-gray-500 mt-1">
                                <span id="message-count">0</span>/2000 characters
                            </div>
                        </div>

                        <!-- Preferred Contact Method -->
                        <div>
                            <span class="form-label">Preferred Contact Method</span>
                            <div class="contact-radio-group">
                                <div class="form-radio-row">
                                    <input type="radio" name="contact_method" id="contact_email" value="email" class="form-radio">
                                    <label for="contact_email" class="form-label-inline">Email</label>
                                </div>
                                <div class="form-radio-row">
                                    <input type="radio" name="contact_method" id="contact_phone" value="phone" class="form-radio">
                                    <label for="contact_phone" class="form-label-inline">Phone</label>
                                </div>
                                <div class="form-radio-row">
                                    <input type="radio" name="contact_method" id="contact_either" value="either" class="form-radio" checked>
                                    <label for="contact_either" class="form-label-inline">Either is fine</label>
                                </div>
                            </div>
                        </div>

                        <!-- How did you hear about us? -->
                        <div>
                            <label for="source" class="form-label">How did you hear about us?</label>
                            <select name="source" id="source"
                                class="form-input">
                                <option value="" selected>Select an option</option>
                                <option value="google">Google Search</option>
                                <option value="social">Social Media</option>
                                <option value="referral">Referral</option>
                                <option value="event">Conference/Event</option>
                                <option value="other">Other</option>
                            </select>
                        </div>
                    </div>
                </div>

                <!-- Privacy Policy -->
                <div class="flex items-start pt-2">
                    <div class="flex items-center h-5">
                        <input id="privacy_policy" name="privacy_policy" type="checkbox" required
                            class="form-checkbox">
                    </div>
                    <div class="ml-3 text-sm">
                        <label for="privacy_policy" class="tag-item">I agree to the <a href="/privacy" class="form-link">privacy policy</a> <span class="text-red-500">*</span></label>
                    </div>
                </div>

                <!-- Submit Button -->
                <div class="pt-4 mt-24">
                    <button type="submit"
                        class="btn btn--primary contact-submit">
                        Send Message
                    </button>
                </div>

                <!-- Form Status Messages -->
                <div id="form-status" class="form-status hidden"></div>
            </form>
        </div>
    </div>
</section>

<?php $this->end() ?>

<?php $this->push('scripts') ?>
    <script src="/js/contact-form.js"></script>
<?php $this->end() ?>
