<?php $this->layout('layouts/app') ?>

<?php $this->start('main') ?>
<div class="py-12 bg-white">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="lg:text-center">
            <h2 class="text-3xl font-extrabold text-gray-900 sm:text-4xl">
                Contact Us
            </h2>
            <p class="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto">
                Have questions? Send us a message and we'll get back to you as soon as possible.
            </p>
        </div>

        <div class="mt-10">
            <form id="contact-form" method="POST" action="/contact" class="max-w-2xl mx-auto space-y-6 bg-white p-6 rounded-lg shadow-md">
                <?php // CSRF tokens (generated by Slim\Csrf\Guard) ?>
                <input type="hidden" name="<?= htmlspecialchars($csrf_name_key ?? '') ?>" value="<?= htmlspecialchars($csrf_name ?? '') ?>">
                <input type="hidden" name="<?= htmlspecialchars($csrf_value_key ?? '') ?>" value="<?= htmlspecialchars($csrf_value ?? '') ?>">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
                    <!-- Left Column -->
                    <div class="space-y-6">
                        <!-- Full Name -->
                        <div>
                            <label for="name" class="block text-sm font-medium text-gray-700">Full Name <span class="text-red-500">*</span></label>
                            <input type="text" name="name" id="name" required minlength="2" maxlength="100"
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2">
                        </div>

                        <!-- Email -->
                        <div>
                            <label for="email" class="block text-sm font-medium text-gray-700">Email <span class="text-red-500">*</span></label>
                            <input type="email" name="email" id="email" required
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2">
                        </div>

                        <!-- Phone Number -->
                        <div>
                            <label for="phone" class="block text-sm font-medium text-gray-700">Phone Number</label>
                            <input type="tel" name="phone" id="phone"
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                                placeholder="+1 (555) 123-4567">
                        </div>

                        <!-- Company Name -->
                        <div>
                            <label for="company" class="block text-sm font-medium text-gray-700">Company Name</label>
                            <input type="text" name="company" id="company" maxlength="100"
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2">
                        </div>

                        <!-- Project Type -->
                        <div>
                            <label for="project_type" class="block text-sm font-medium text-gray-700">Project Type <span class="text-red-500">*</span></label>
                            <select name="project_type" id="project_type" required
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2">
                                <option value="" disabled selected>Select project type</option>
                                <option value="web">Web Development</option>
                                <option value="software">Software Development</option>
                                <option value="consulting">Consulting</option>
                                <option value="other">Other</option>
                            </select>
                        </div>
                    </div>

                    <!-- Right Column -->
                    <div class="space-y-6">
                        <!-- Project Description -->
                        <div class="flex flex-col">
                            <label for="message" class="block text-sm font-medium text-gray-700">Project Description <span class="text-red-500">*</span></label>
                            <div class="flex-1">
                                <textarea id="message" name="message" rows="8" required minlength="10" maxlength="2000"
                                    class="mt-1 block w-full h-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                                    placeholder="Tell us about your project..."></textarea>
                            </div>
                            <div class="text-right text-xs text-gray-500 mt-1">
                                <span id="message-count">0</span>/2000 characters
                            </div>
                        </div>

                        <!-- Preferred Contact Method -->
                        <div>
                            <span class="block text-sm font-medium text-gray-700">Preferred Contact Method</span>
                            <div class="mt-2 mb-6 space-y-2">
                                <div class="flex items-center">
                                    <input type="radio" name="contact_method" id="contact_email" value="email" class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300">
                                    <label for="contact_email" class="ml-2 block text-sm text-gray-700">Email</label>
                                </div>
                                <div class="flex items-center">
                                    <input type="radio" name="contact_method" id="contact_phone" value="phone" class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300">
                                    <label for="contact_phone" class="ml-2 block text-sm text-gray-700">Phone</label>
                                </div>
                                <div class="flex items-center">
                                    <input type="radio" name="contact_method" id="contact_either" value="either" class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300" checked>
                                    <label for="contact_either" class="ml-2 block text-sm text-gray-700">Either is fine</label>
                                </div>
                            </div>
                        </div>

                        <!-- How did you hear about us? -->
                        <div>
                            <label for="source" class="block text-sm font-medium text-gray-700">How did you hear about us?</label>
                            <select name="source" id="source"
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2">
                                <option value="" selected>Select an option</option>
                                <option value="google">Google Search</option>
                                <option value="social">Social Media</option>
                                <option value="referral">Referral</option>
                                <option value="event">Conference/Event</option>
                                <option value="other">Other</option>
                            </select>
                        </div>
                    </div>
                </div>

                <!-- Privacy Policy -->
                <div class="flex items-start pt-2">
                    <div class="flex items-center h-5">
                        <input id="privacy_policy" name="privacy_policy" type="checkbox" required
                            class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded">
                    </div>
                    <div class="ml-3 text-sm">
                        <label for="privacy_policy" class="font-medium text-gray-700">I agree to the <a href="/privacy" class="text-indigo-600 hover:text-indigo-500">privacy policy</a> <span class="text-red-500">*</span></label>
                    </div>
                </div>

                <!-- Submit Button -->
                <div class="pt-4 mt-24">
                    <button type="submit"
                        class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        Send Message
                    </button>
                </div>

                <!-- Form Status Messages -->
                <div id="form-status" class="hidden mt-4 p-4 rounded-md"></div>
            </form>
        </div>
    </div>
</div>

<?php $this->end() ?>

<?php $this->push('scripts') ?>
    <script src="/js/contact-form.js"></script>
<?php $this->end() ?>
